Updated herolte device page
Halium/docs pull request #160
Opened 2020-08-29 08:10 UTC by abkro

Edited herolte.rst page with links to updated WIP device and kernel repos and did a couple of other minor edits to the page.

2020-08-30 18:26 UTC, doniks requested changes
two small remarks below. but more importantly, git says it conflicts!

2020-08-30 18:26 UTC, doniks commented on supplementary/devices/herolte.rst
> -* Now, you should once more be able to either boot normally or boot into recovery, whichever you wish.
s?

2020-08-30 18:26 UTC, doniks commented on supplementary/devices/h815.rst
> +===========================
underline is too long

2020-08-30 21:41 UTC, abkro commented
I have dealt with the conflicts now as far as I can see. I don't understand the last one. Tried multiple times....

2021-01-24 12:52 UTC, doniks approved these changes

2021-01-24 13:14 UTC, doniks commented
hi @abkro . I've resolved the conflicts. Had to add a column in the table (works/doesn't work) - please check

2021-02-05 00:26 UTC, doniks commented
no objections. I'll merge

2021-02-05 00:26 UTC, merged